services:
  # Main reverse proxy service (public web)
  - type: web
    name: mcp-proxy
    env: docker
    plan: starter
    rootDir: .
    dockerfilePath: proxy.Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
    healthCheckPath: /healthz

  # All 50+ Klavis MCP servers (private services)
  
  # CRM & Sales/RevOps
  - type: privateService
    name: mcp-affinity
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/affinity/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-attio
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/attio/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-close
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/close/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-hubspot
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/hubspot/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-salesforce
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/salesforce/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-gong
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/gong/Dockerfile
    autoDeploy: true

  # Project & Issue Tracking
  - type: privateService
    name: mcp-asana
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/asana/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-clickup
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/clickup/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-jira
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/jira/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-linear
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/linear/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-monday
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/monday/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-motion
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/motion/Dockerfile
    autoDeploy: true

  # Support & Helpdesk
  - type: privateService
    name: mcp-freshdesk
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/freshdesk/Dockerfile
    autoDeploy: true

  # Marketing & Outreach
  - type: privateService
    name: mcp-mailchimp
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/mailchimp/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-resend
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/resend/Dockerfile
    autoDeploy: true

  # Communication & Meetings
  - type: privateService
    name: mcp-slack
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/slack/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-discord
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/discord/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-gmail
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/gmail/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-google-calendar
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_calendar/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-google-meet
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_meet/dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-twilio
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/twilio/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-whatsapp
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/whatsapp/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-cal-com
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/cal_com/Dockerfile
    autoDeploy: true

  # Files, Docs & Knowledge
  - type: privateService
    name: mcp-confluence
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/confluence/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-notion
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/notion/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-google-docs
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_docs/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-google-sheets
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_sheets/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-google-slides
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_slides/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-google-drive
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_drive/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-dropbox
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/dropbox/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-onedrive
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/onedrive/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-wordpress
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/wordpress/Dockerfile
    autoDeploy: true

  # Databases & Data Platforms
  - type: privateService
    name: mcp-postgres
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/postgres/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-supabase
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/supabase/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-airtable
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/airtable/Dockerfile
    autoDeploy: true

  # E-commerce, Payments & Finance
  - type: privateService
    name: mcp-shopify
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/shopify/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-stripe
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/stripe/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-quickbooks
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/quickbooks/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-moneybird
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/moneybird/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-coinbase
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/coinbase/Dockerfile
    autoDeploy: true

  # Developer Tools
  - type: privateService
    name: mcp-github
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/github/Dockerfile
    autoDeploy: true

  # Search, Research & Web Crawling
  - type: privateService
    name: mcp-brave-search
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/brave_search/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-exa
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/exa/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-tavily
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/tavily/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-firecrawl
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/firecrawl/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-firecrawl-deep-research
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/firecrawl_deep_research/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-hacker-news
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/hacker_news/Dockerfile
    autoDeploy: true

  # Social & Media
  - type: privateService
    name: mcp-linkedin
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/linkedin/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-youtube
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/youtube/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-spotify
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/spotify/Dockerfile
    autoDeploy: true

  # AI/LLM & Content Utilities
  - type: privateService
    name: mcp-openrouter
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/openrouter/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-heygen
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/heygen/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-markitdown
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/markitdown/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-pandoc
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/pandoc/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-report-generation
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/report_generation/Dockerfile
    autoDeploy: true

  - type: privateService
    name: mcp-mem0
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/mem0/Dockerfile
    autoDeploy: true

  # Jobs & Recruiting
  - type: privateService
    name: mcp-google-jobs
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/google_jobs/Dockerfile
    autoDeploy: true

  # Analytics & BI
  - type: privateService
    name: mcp-mixpanel
    env: docker
    rootDir: .
    dockerfilePath: mcp_servers/mixpanel/Dockerfile
    autoDeploy: true
