services:
  # Single service running all MCPs - only $7/month!
  - type: web
    name: mcp-all-in-one
    runtime: docker
    repo: https://github.com/VihariKanukollu/klavis
    rootDir: .
    dockerfilePath: ./multi-mcp-v2.Dockerfile
    autoDeploy: true
    branch: main
    region: oregon
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /healthz
